from routes.dashboard import *
from routes.product_list import *
from routes.product_edit import *
from routes.product_add import *
from routes.category import *
from routes.order import *
from routes.order_detail import *
from routes.invoice import *
from routes.user_registration import *
